const paths = require('./openapi.paths');
const schemas = require('./openapi.schemas');

/** @type {import('swagger-jsdoc').OAS3Definition} */
module.exports = {
  openapi: '3.0.0',
  info: {
    title: 'Denton Vision Art API',
    version: '1.0.0',
    description: [
      'REST API for **mines**, **minerals**, **yellow machines**, offers, messaging, payments, and users.',
      '',
      '## Frontend quick start',
      '',
      '| Resource | Base path | Auth |',
      '|----------|-----------|------|',
      '| Mines | `GET/POST /api/mines` | Public (create/update as implemented) |',
      '| Minerals | `GET /api/minerals` | Public read; `POST/PATCH/DELETE` need JWT + role `admin` or `mineral-manager` |',
      '| Yellow machines | `GET/POST /api/yellow-machines` | Public |',
      '| Auth | `POST /api/auth/login` | Returns `token` for Bearer auth |',
      '',
      '**OpenAPI JSON (codegen):** `GET /openapi.json`',
      '',
      '**Swagger UI:** `/api-docs` — use **Authorize** with `Bearer <token>` for protected routes.',
      '',
      '### Multipart create / update',
      '- Use `Content-Type: multipart/form-data` and `FormData` in the browser.',
      '- Numbers and booleans are sent as **strings** (e.g. `price`, `forSale`, `rentalAvailable`).',
      '- Nested objects: `rates`, `rental`, `coordinates` as **JSON strings**.',
      '- Files: field names `images`, `documents`, `media` (append multiple with the same key).',
      '- On update, remove files with `deleteImageIds`, `deleteDocumentIds`, or `deleteMediaIds` (JSON array or comma-separated `_id` from nested `images` / `documents` / `media`).',
      '',
      '### TypeScript client generation',
      '```bash',
      'npx openapi-typescript http://localhost:5000/openapi.json -o src/api/schema.d.ts',
      '# or',
      'npx @openapitools/openapi-generator-cli generate -i http://localhost:5000/openapi.json -g typescript-fetch -o src/api',
      '```',
      '',
      'Each operation includes an `operationId` suitable for generated function names.',
      '',
      '### Route ordering note',
      'Static segments like `/owner/{ownerId}` and `/search/{query}` must be called with exact paths. If a static segment is mistaken for `:id`, reorder routes in the Express router.',
    ].join('\n'),
  },
  servers: [
    { url: 'http://localhost:5000', description: 'Local development' },
    {
      url: '{protocol}://{host}',
      description: 'Custom host',
      variables: {
        protocol: { default: 'http', enum: ['http', 'https'] },
        host: { default: 'localhost:5000' },
      },
    },
  ],
  tags: [
    { name: 'System', description: 'Health, JWT test, standalone file uploads' },
    { name: 'Auth', description: 'Register, login' },
    { name: 'Users', description: 'User CRUD (`/api/user`)' },
    { name: 'Mines', description: 'Mine listings — documents (PDF, etc.) and media (pictures)' },
    { name: 'Minerals', description: 'Mineral catalog — images, documents, geo search' },
    { name: 'Yellow Machines', description: 'Heavy equipment — rental, sale, rates, media & documents' },
    { name: 'Offers', description: 'Bids on mines or minerals' },
    { name: 'Messages', description: 'Conversations and DMs' },
    { name: 'Analytics', description: 'Dashboard stats' },
    { name: 'Payments', description: 'Stripe and Ozow' },
  ],
  paths,
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'JWT from `POST /api/auth/login` or `POST /api/auth/register` — response field `token`',
      },
    },
    schemas,
  },
};
